ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: route53
  paths:
    - /
  hosts:
    - host: hello-world.brian-onboarding.hillghost.com
      paths: ["/"]
  tls:
    - secretName: hello-world-cert
      hosts:
        - hello-world.brian-onboarding.hillghost.com